name: Artifacts
on: [push]
env:
  ARTIFACTS_NAME: myartifacts
jobs:
  main:
    runs-on:  ubuntu-latest
    steps: 
      - name: Checkou out the code
        uses:  actions/checkout@v2
      - name:  upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
